spring:
  application:
    name: challenge
  datasource:
    url: jdbc:postgresql://localhost:5432/challenge_db
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Configuración para desactivar la serialización de propiedades desconocidas
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Mexico_City

# Configuración para errores detallados
server:
  error:
    include-message: always
    include-binding-errors: always